openapi: '3.0.3'
info:
  title: Products API
  description: API for managing products
  version: '1.0'
servers:
  - url: https://rfme377yra.execute-api.eu-north-1.amazonaws.com/prod
paths:
  /products:
    get:
      tags:
        - Products
      summary: Get product list
      responses:
        '200':
          description: Product list retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: uuid
                        title:
                          type: string
                        description:
                          type: string
                        price:
                          type: number
  /products/{id}:
    get:
      tags:
        - Products
      summary: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: uuid
      responses:
        '200':
          description: Product retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        description: uuid
                      title:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
        '404':
          description: Product not found
          content:
            application/json:
              schema:
               type: object
               properties:
                 message:
                  type: string
                  example: Product not found
